package manjuu.mbg.entity;

public class HallInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HALL_INFO.HALL_ID
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    private String hallId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HALL_INFO.HALL_ID
     *
     * @return the value of HALL_INFO.HALL_ID
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public String getHallId() {
        return hallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HALL_INFO.HALL_ID
     *
     * @param hallId the value for HALL_INFO.HALL_ID
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public void setHallId(String hallId) {
        this.hallId = hallId;
    }
}