package manjuu.mbg.entity;

public class HallInfo extends HallInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HALL_INFO.HALL_NAME
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    private String hallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HALL_INFO.CONVERSION_RATE
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    private Double conversionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HALL_INFO.DATA_SITE
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    private String dataSite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HALL_INFO.HALL_NAME
     *
     * @return the value of HALL_INFO.HALL_NAME
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public String getHallName() {
        return hallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HALL_INFO.HALL_NAME
     *
     * @param hallName the value for HALL_INFO.HALL_NAME
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public void setHallName(String hallName) {
        this.hallName = hallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HALL_INFO.CONVERSION_RATE
     *
     * @return the value of HALL_INFO.CONVERSION_RATE
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public Double getConversionRate() {
        return conversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HALL_INFO.CONVERSION_RATE
     *
     * @param conversionRate the value for HALL_INFO.CONVERSION_RATE
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public void setConversionRate(Double conversionRate) {
        this.conversionRate = conversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HALL_INFO.DATA_SITE
     *
     * @return the value of HALL_INFO.DATA_SITE
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public String getDataSite() {
        return dataSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HALL_INFO.DATA_SITE
     *
     * @param dataSite the value for HALL_INFO.DATA_SITE
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    public void setDataSite(String dataSite) {
        this.dataSite = dataSite;
    }
}