package manjuu.mbg.entity;

import java.util.ArrayList;
import java.util.List;

public class MHallInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public MHallInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHallIdIsNull() {
            addCriterion("HALL_ID is null");
            return (Criteria) this;
        }

        public Criteria andHallIdIsNotNull() {
            addCriterion("HALL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHallIdEqualTo(String value) {
            addCriterion("HALL_ID =", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdNotEqualTo(String value) {
            addCriterion("HALL_ID <>", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdGreaterThan(String value) {
            addCriterion("HALL_ID >", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdGreaterThanOrEqualTo(String value) {
            addCriterion("HALL_ID >=", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdLessThan(String value) {
            addCriterion("HALL_ID <", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdLessThanOrEqualTo(String value) {
            addCriterion("HALL_ID <=", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdLike(String value) {
            addCriterion("HALL_ID like", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdNotLike(String value) {
            addCriterion("HALL_ID not like", value, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdIn(List<String> values) {
            addCriterion("HALL_ID in", values, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdNotIn(List<String> values) {
            addCriterion("HALL_ID not in", values, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdBetween(String value1, String value2) {
            addCriterion("HALL_ID between", value1, value2, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallIdNotBetween(String value1, String value2) {
            addCriterion("HALL_ID not between", value1, value2, "hallId");
            return (Criteria) this;
        }

        public Criteria andHallNameIsNull() {
            addCriterion("HALL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andHallNameIsNotNull() {
            addCriterion("HALL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andHallNameEqualTo(String value) {
            addCriterion("HALL_NAME =", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameNotEqualTo(String value) {
            addCriterion("HALL_NAME <>", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameGreaterThan(String value) {
            addCriterion("HALL_NAME >", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameGreaterThanOrEqualTo(String value) {
            addCriterion("HALL_NAME >=", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameLessThan(String value) {
            addCriterion("HALL_NAME <", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameLessThanOrEqualTo(String value) {
            addCriterion("HALL_NAME <=", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameLike(String value) {
            addCriterion("HALL_NAME like", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameNotLike(String value) {
            addCriterion("HALL_NAME not like", value, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameIn(List<String> values) {
            addCriterion("HALL_NAME in", values, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameNotIn(List<String> values) {
            addCriterion("HALL_NAME not in", values, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameBetween(String value1, String value2) {
            addCriterion("HALL_NAME between", value1, value2, "hallName");
            return (Criteria) this;
        }

        public Criteria andHallNameNotBetween(String value1, String value2) {
            addCriterion("HALL_NAME not between", value1, value2, "hallName");
            return (Criteria) this;
        }

        public Criteria andConversionRateIsNull() {
            addCriterion("CONVERSION_RATE is null");
            return (Criteria) this;
        }

        public Criteria andConversionRateIsNotNull() {
            addCriterion("CONVERSION_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andConversionRateEqualTo(Double value) {
            addCriterion("CONVERSION_RATE =", value, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateNotEqualTo(Double value) {
            addCriterion("CONVERSION_RATE <>", value, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateGreaterThan(Double value) {
            addCriterion("CONVERSION_RATE >", value, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateGreaterThanOrEqualTo(Double value) {
            addCriterion("CONVERSION_RATE >=", value, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateLessThan(Double value) {
            addCriterion("CONVERSION_RATE <", value, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateLessThanOrEqualTo(Double value) {
            addCriterion("CONVERSION_RATE <=", value, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateIn(List<Double> values) {
            addCriterion("CONVERSION_RATE in", values, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateNotIn(List<Double> values) {
            addCriterion("CONVERSION_RATE not in", values, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateBetween(Double value1, Double value2) {
            addCriterion("CONVERSION_RATE between", value1, value2, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andConversionRateNotBetween(Double value1, Double value2) {
            addCriterion("CONVERSION_RATE not between", value1, value2, "conversionRate");
            return (Criteria) this;
        }

        public Criteria andDataSiteIsNull() {
            addCriterion("DATA_SITE is null");
            return (Criteria) this;
        }

        public Criteria andDataSiteIsNotNull() {
            addCriterion("DATA_SITE is not null");
            return (Criteria) this;
        }

        public Criteria andDataSiteEqualTo(String value) {
            addCriterion("DATA_SITE =", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteNotEqualTo(String value) {
            addCriterion("DATA_SITE <>", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteGreaterThan(String value) {
            addCriterion("DATA_SITE >", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_SITE >=", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteLessThan(String value) {
            addCriterion("DATA_SITE <", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteLessThanOrEqualTo(String value) {
            addCriterion("DATA_SITE <=", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteLike(String value) {
            addCriterion("DATA_SITE like", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteNotLike(String value) {
            addCriterion("DATA_SITE not like", value, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteIn(List<String> values) {
            addCriterion("DATA_SITE in", values, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteNotIn(List<String> values) {
            addCriterion("DATA_SITE not in", values, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteBetween(String value1, String value2) {
            addCriterion("DATA_SITE between", value1, value2, "dataSite");
            return (Criteria) this;
        }

        public Criteria andDataSiteNotBetween(String value1, String value2) {
            addCriterion("DATA_SITE not between", value1, value2, "dataSite");
            return (Criteria) this;
        }

        public Criteria andMachineUrlIsNull() {
            addCriterion("MACHINE_URL is null");
            return (Criteria) this;
        }

        public Criteria andMachineUrlIsNotNull() {
            addCriterion("MACHINE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andMachineUrlEqualTo(String value) {
            addCriterion("MACHINE_URL =", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlNotEqualTo(String value) {
            addCriterion("MACHINE_URL <>", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlGreaterThan(String value) {
            addCriterion("MACHINE_URL >", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlGreaterThanOrEqualTo(String value) {
            addCriterion("MACHINE_URL >=", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlLessThan(String value) {
            addCriterion("MACHINE_URL <", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlLessThanOrEqualTo(String value) {
            addCriterion("MACHINE_URL <=", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlLike(String value) {
            addCriterion("MACHINE_URL like", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlNotLike(String value) {
            addCriterion("MACHINE_URL not like", value, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlIn(List<String> values) {
            addCriterion("MACHINE_URL in", values, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlNotIn(List<String> values) {
            addCriterion("MACHINE_URL not in", values, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlBetween(String value1, String value2) {
            addCriterion("MACHINE_URL between", value1, value2, "machineUrl");
            return (Criteria) this;
        }

        public Criteria andMachineUrlNotBetween(String value1, String value2) {
            addCriterion("MACHINE_URL not between", value1, value2, "machineUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 07 01:05:47 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_HALL_INFO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}