package manjuu.mbg.entity;

public class MHallInfo extends MHallInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_HALL_INFO.HALL_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String hallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_HALL_INFO.CONVERSION_RATE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Double conversionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_HALL_INFO.DATA_SITE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String dataSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_HALL_INFO.MACHINE_URL
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String machineUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_HALL_INFO.HALL_NAME
     *
     * @return the value of M_HALL_INFO.HALL_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getHallName() {
        return hallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_HALL_INFO.HALL_NAME
     *
     * @param hallName the value for M_HALL_INFO.HALL_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setHallName(String hallName) {
        this.hallName = hallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_HALL_INFO.CONVERSION_RATE
     *
     * @return the value of M_HALL_INFO.CONVERSION_RATE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Double getConversionRate() {
        return conversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_HALL_INFO.CONVERSION_RATE
     *
     * @param conversionRate the value for M_HALL_INFO.CONVERSION_RATE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setConversionRate(Double conversionRate) {
        this.conversionRate = conversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_HALL_INFO.DATA_SITE
     *
     * @return the value of M_HALL_INFO.DATA_SITE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getDataSite() {
        return dataSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_HALL_INFO.DATA_SITE
     *
     * @param dataSite the value for M_HALL_INFO.DATA_SITE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setDataSite(String dataSite) {
        this.dataSite = dataSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_HALL_INFO.MACHINE_URL
     *
     * @return the value of M_HALL_INFO.MACHINE_URL
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getMachineUrl() {
        return machineUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_HALL_INFO.MACHINE_URL
     *
     * @param machineUrl the value for M_HALL_INFO.MACHINE_URL
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setMachineUrl(String machineUrl) {
        this.machineUrl = machineUrl;
    }
}