package manjuu.mbg.entity;

public class MMachineListKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MACHINE_LIST.HALL_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String hallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MACHINE_LIST.MACHINE_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Integer machineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MACHINE_LIST.HALL_ID
     *
     * @return the value of M_MACHINE_LIST.HALL_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getHallId() {
        return hallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MACHINE_LIST.HALL_ID
     *
     * @param hallId the value for M_MACHINE_LIST.HALL_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setHallId(String hallId) {
        this.hallId = hallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MACHINE_LIST.MACHINE_ID
     *
     * @return the value of M_MACHINE_LIST.MACHINE_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MACHINE_LIST.MACHINE_ID
     *
     * @param machineId the value for M_MACHINE_LIST.MACHINE_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }
}