package manjuu.mbg.entity;

import java.util.Date;

public class TMachineData extends TMachineDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.HALL_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String hallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.ACQUISITION_DATE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Date acquisitionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.MACHINE_NO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String machineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.MACHINE_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String machineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.GAMES
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Integer games;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.PAYOUT
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Integer payout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.HALL_ID
     *
     * @return the value of T_MACHINE_DATA.HALL_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getHallId() {
        return hallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.HALL_ID
     *
     * @param hallId the value for T_MACHINE_DATA.HALL_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setHallId(String hallId) {
        this.hallId = hallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.ACQUISITION_DATE
     *
     * @return the value of T_MACHINE_DATA.ACQUISITION_DATE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Date getAcquisitionDate() {
        return acquisitionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.ACQUISITION_DATE
     *
     * @param acquisitionDate the value for T_MACHINE_DATA.ACQUISITION_DATE
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setAcquisitionDate(Date acquisitionDate) {
        this.acquisitionDate = acquisitionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.MACHINE_NO
     *
     * @return the value of T_MACHINE_DATA.MACHINE_NO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getMachineNo() {
        return machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.MACHINE_NO
     *
     * @param machineNo the value for T_MACHINE_DATA.MACHINE_NO
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setMachineNo(String machineNo) {
        this.machineNo = machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.MACHINE_NAME
     *
     * @return the value of T_MACHINE_DATA.MACHINE_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.MACHINE_NAME
     *
     * @param machineName the value for T_MACHINE_DATA.MACHINE_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.GAMES
     *
     * @return the value of T_MACHINE_DATA.GAMES
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Integer getGames() {
        return games;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.GAMES
     *
     * @param games the value for T_MACHINE_DATA.GAMES
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setGames(Integer games) {
        this.games = games;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.PAYOUT
     *
     * @return the value of T_MACHINE_DATA.PAYOUT
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Integer getPayout() {
        return payout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.PAYOUT
     *
     * @param payout the value for T_MACHINE_DATA.PAYOUT
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setPayout(Integer payout) {
        this.payout = payout;
    }
}