package manjuu.mbg.entity;

public class TMachineDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MACHINE_DATA.DATA_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Integer dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MACHINE_DATA.DATA_ID
     *
     * @return the value of T_MACHINE_DATA.DATA_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MACHINE_DATA.DATA_ID
     *
     * @param dataId the value for T_MACHINE_DATA.DATA_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }
}