package manjuu.mbg.entity;

import java.util.Date;

public class TUserInfo extends TUserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.USER_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.USER_PASSWORD
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.USER_AUTHORITY
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String userAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.USER_INFOcol
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private String userInfocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.REGISTER_TIME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Date registerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.USER_NAME
     *
     * @return the value of T_USER_INFO.USER_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.USER_NAME
     *
     * @param userName the value for T_USER_INFO.USER_NAME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.USER_PASSWORD
     *
     * @return the value of T_USER_INFO.USER_PASSWORD
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.USER_PASSWORD
     *
     * @param userPassword the value for T_USER_INFO.USER_PASSWORD
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.USER_AUTHORITY
     *
     * @return the value of T_USER_INFO.USER_AUTHORITY
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getUserAuthority() {
        return userAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.USER_AUTHORITY
     *
     * @param userAuthority the value for T_USER_INFO.USER_AUTHORITY
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setUserAuthority(String userAuthority) {
        this.userAuthority = userAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.USER_INFOcol
     *
     * @return the value of T_USER_INFO.USER_INFOcol
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public String getUserInfocol() {
        return userInfocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.USER_INFOcol
     *
     * @param userInfocol the value for T_USER_INFO.USER_INFOcol
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setUserInfocol(String userInfocol) {
        this.userInfocol = userInfocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.UPDATE_TIME
     *
     * @return the value of T_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.REGISTER_TIME
     *
     * @return the value of T_USER_INFO.REGISTER_TIME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.REGISTER_TIME
     *
     * @param registerTime the value for T_USER_INFO.REGISTER_TIME
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }
}