package manjuu.mbg.entity;

public class TUserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.USER_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.USER_ID
     *
     * @return the value of T_USER_INFO.USER_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.USER_ID
     *
     * @param userId the value for T_USER_INFO.USER_ID
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}