package manjuu.mbg.mapper;

import java.util.List;
import manjuu.mbg.entity.HallInfo;
import manjuu.mbg.entity.HallInfoExample;
import manjuu.mbg.entity.HallInfoKey;
import org.apache.ibatis.annotations.Param;

public interface HallInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int countByExample(HallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int deleteByExample(HallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int deleteByPrimaryKey(HallInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int insert(HallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int insertSelective(HallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    List<HallInfo> selectByExample(HallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    HallInfo selectByPrimaryKey(HallInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int updateByExampleSelective(@Param("record") HallInfo record, @Param("example") HallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int updateByExample(@Param("record") HallInfo record, @Param("example") HallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int updateByPrimaryKeySelective(HallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HALL_INFO
     *
     * @mbggenerated Thu Jun 16 23:53:46 JST 2016
     */
    int updateByPrimaryKey(HallInfo record);
}