package manjuu.mbg.mapper;

import java.util.List;
import manjuu.mbg.entity.TMachineData;
import manjuu.mbg.entity.TMachineDataExample;
import manjuu.mbg.entity.TMachineDataKey;
import org.apache.ibatis.annotations.Param;

public interface TMachineDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int countByExample(TMachineDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int deleteByExample(TMachineDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int deleteByPrimaryKey(TMachineDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int insert(TMachineData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int insertSelective(TMachineData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    List<TMachineData> selectByExample(TMachineDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    TMachineData selectByPrimaryKey(TMachineDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int updateByExampleSelective(@Param("record") TMachineData record, @Param("example") TMachineDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int updateByExample(@Param("record") TMachineData record, @Param("example") TMachineDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int updateByPrimaryKeySelective(TMachineData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MACHINE_DATA
     *
     * @mbggenerated Sun Aug 07 01:05:47 JST 2016
     */
    int updateByPrimaryKey(TMachineData record);
}