package manjuu.model.entity;

import java.util.Date;

public class MachineData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACHINE_DATA.SYUTOKUBI
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    private Date syutokubi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACHINE_DATA.MACHINE_NO
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    private String machineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACHINE_DATA.MACHINE_NAME
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    private String machineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACHINE_DATA.GAMES
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    private Integer games;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MACHINE_DATA.PAYOUT
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    private Integer payout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACHINE_DATA.SYUTOKUBI
     *
     * @return the value of MACHINE_DATA.SYUTOKUBI
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public Date getSyutokubi() {
        return syutokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACHINE_DATA.SYUTOKUBI
     *
     * @param syutokubi the value for MACHINE_DATA.SYUTOKUBI
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public void setSyutokubi(Date syutokubi) {
        this.syutokubi = syutokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACHINE_DATA.MACHINE_NO
     *
     * @return the value of MACHINE_DATA.MACHINE_NO
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public String getMachineNo() {
        return machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACHINE_DATA.MACHINE_NO
     *
     * @param machineNo the value for MACHINE_DATA.MACHINE_NO
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public void setMachineNo(String machineNo) {
        this.machineNo = machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACHINE_DATA.MACHINE_NAME
     *
     * @return the value of MACHINE_DATA.MACHINE_NAME
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACHINE_DATA.MACHINE_NAME
     *
     * @param machineName the value for MACHINE_DATA.MACHINE_NAME
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACHINE_DATA.GAMES
     *
     * @return the value of MACHINE_DATA.GAMES
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public Integer getGames() {
        return games;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACHINE_DATA.GAMES
     *
     * @param games the value for MACHINE_DATA.GAMES
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public void setGames(Integer games) {
        this.games = games;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MACHINE_DATA.PAYOUT
     *
     * @return the value of MACHINE_DATA.PAYOUT
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public Integer getPayout() {
        return payout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MACHINE_DATA.PAYOUT
     *
     * @param payout the value for MACHINE_DATA.PAYOUT
     *
     * @mbggenerated Sat May 21 00:05:19 JST 2016
     */
    public void setPayout(Integer payout) {
        this.payout = payout;
    }
}